### ISSUE TITLE
Make xxhash optional

### ISSUE THREAD

**Issue by burningTyger** [sebastian-software/rollup-plugin-rebase#11]
It would make things a lot easier if xxhash wasn't used by default. I'm using rollup in an electron app and using a native library makes things just more complicated for no reason. I don't think using a different non native library will slow your plugin down that much :)

**Comment by swernerx** [comment]
Thanks for the feedback. Much appreciated. The typical usage model is around using rollup on the command line. This is for what it is designed right now. I am not deep into Electron, not sure what exactly the issue is.

You can of course use different algorithms via the hashOptions flag. This does not influence the installation of dependencies though - if that's the problem.
